version: 1
body:
  patterns:
    - '#\d+'
  error: The body has to include an issue reference like `#0`
branch:
  patterns:
    - 'issue-\d{1,}-[a-z0-9-]+'
  error: Branch must be called `issue-{id}-{short description}`
